# Generated by Django 5.2.4 on 2025-08-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_market_orders_trades_wallet_wallettransaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='asset_name',
        ),
        migrations.AddField(
            model_name='market',
            name='name',
            field=models.CharField(default='BITCOIN', max_length=50),
        ),
        migrations.AddField(
            model_name='market',
            name='symbol',
            field=models.CharField(default='BTC', max_length=10, unique=True),
        ),
    ]
