# Generated by Django 5.2.4 on 2025-08-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_market_asset_name_market_name_market_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='symbol',
            field=models.CharField(default='BTC', max_length=10),
        ),
    ]
