# Generated by Django 5.2.4 on 2025-08-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_market_last_updated_alter_market_symbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(default='BTC', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='wallet',
            name='type',
            field=models.CharField(default='INR', max_length=10),
        ),
    ]
