# Generated by Django 5.2.4 on 2025-08-04 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_crypto_wallet_type'),
    ]

    operations = [
        
        migrations.RemoveField(
            model_name='wallet',
            name='type',
        ),
    ]
