# Generated by Django 5.2.4 on 2025-08-04 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_wallet_unique_together_wallet_crypto_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together=set(),
        ),
    ]
