# Generated by Django 5.2.4 on 2025-08-04 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_wallet_unique_together_remove_wallet_crypto'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='crypto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.crypto'),
        ),
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('user', 'crypto')},
        ),
    ]
