# Generated by Django 5.2.4 on 2025-08-05 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_wallet_crypto_alter_wallet_unique_together'),
    ]

    operations = [
       
    ]
