# Generated by Django 5.2.4 on 2025-08-05 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_orders_base_currency_and_more'),
    ]

    operations = [
    ]
