# Generated by Django 5.2.4 on 2025-08-05 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_alter_orders_base_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='base_currency',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='quote_currency',
        ),
    ]
