# Generated by Django 5.2.4 on 2025-08-05 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_remove_orders_base_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='base_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base', to='backend.crypto'),
        ),
        migrations.AddField(
            model_name='orders',
            name='quote_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='backend.crypto'),
        ),
    ]
