# Generated by Django 5.2.4 on 2025-08-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_orders_base_currency_orders_quote_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto',
            name='is_crypto',
            field=models.BooleanField(default='True'),
        ),
    ]
