# Generated by Django 5.2.4 on 2025-08-05 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_crypto_is_crypto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crypto',
            new_name='Currency',
        ),
    ]
