# Generated by Django 5.2.4 on 2025-08-05 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_alter_wallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency', to=settings.AUTH_USER_MODEL),
        ),
    ]
