# Generated by Django 5.2.4 on 2025-08-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_portfolio_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='asset',
        ),
    ]
