# Generated by Django 5.2.4 on 2025-08-05 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_portfolio_asset'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='portfolio',
            unique_together={('user', 'asset')},
        ),
    ]
