# Generated by Django 5.2.4 on 2025-08-05 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_alter_portfolio_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currency', to='backend.currency'),
        ),
    ]
